{{ config(materialized='table', schema='analytics') }}

select
    patient_id,
    full_name,
    gender,
    age,
    age_band,
    blood_type,
    city,
    county,
    insurance_status,
    chronic_conditions,
    has_chronic_condition,
    risk_score,
    risk_category,
    registration_date,
    is_active,
    total_visits,
    completed_visits,
    no_show_count,
    cancellation_count,
    distinct_specialties,
    distinct_doctors,
    first_visit_date,
    last_visit_date,
    lifetime_value,
    avg_spend_per_visit,
    avg_rating_given,
    visits_2024,
    visits_2023,
    days_since_last_visit,
    churn_risk,
    engagement_level,
    now()                   as dbt_updated_at
from {{ ref('int_patient_metrics') }}
