{{ config(materialized='table', schema='analytics') }}

select
    appointment_id,
    patient_id,
    doctor_id,
    service_id,
    clinic_id,
    specialty,
    scheduled_at,
    actual_start,
    actual_end,
    status,
    appointment_date,
    appointment_year,
    appointment_month,
    appointment_quarter,
    day_of_week,
    appointment_hour,
    is_weekend,
    is_completed,
    is_cancelled,
    is_no_show,
    is_rescheduled,
    waiting_time_minutes,
    consultation_duration_minutes,
    channel,
    urgency_level,
    referral_source,
    cancellation_reason,
    actual_price,
    discount_pct,
    net_revenue,
    insurance_reimbursement,
    payment_method,
    payment_status,
    rating,
    doctor_name,
    clinic_name,
    clinic_city,
    service_name,
    service_category,
    profitability_margin,
    wait_tier,
    time_of_day,
    now()                   as dbt_updated_at
from {{ ref('int_appointment_metrics') }}
